### ISSUE TITLE
target_urlがリンク切れ

### ISSUE THREAD

**Issue by t2hnd** [opendata-yamanashi/onsen-api#6]
README.md および app/main.py に含まれる以下のリンクが 404 になっていました。

https://www.pref.yamanashi.jp/taiki-sui/documents/h3012011.pdf

以下のURLに修正後動くことを確認していますので、URLの修正が必要そうです。

https://www.pref.yamanashi.jp/documents/6051/h3012012.pdf
(リンク元) https://www.pref.yamanashi.jp/taiki-sui/50295382321.html

よろしくお願いします。

**Comment by yuukis** [comment]
県のサイト側でURLが変更となったようです。

温泉利用施設のオープンデータは以下の2種類があり、
現状、本APIでは「山梨県公共温泉利用施設一覧」を利用しているため、
単純に、リンク切れを修正するだけであれば [1] の URL に置き換えることになります。

[1] 山梨県公共温泉利用施設一覧
https://www.pref.yamanashi.jp/documents/6051/h3012011.pdf

[2] 山梨県民間温泉利用施設一覧
https://www.pref.yamanashi.jp/documents/6051/h3012012.pdf

[2] の結果も返却されるのが望ましいと思いますが、[1]と[2]とで区別できた方がよいと思いますので、
Issueを分けて検討したいです。

このIssueでは、[1] の URL への置き換えのみとします。

**Comment by yuukis** [comment]
> [2] の結果も返却されるのが望ましいと思いますが、[1]と[2]とで区別できた方がよいと思いますので、
Issueを分けて検討したいです。

上記は #7 で検討としたい

**Comment by t2hnd** [comment]
民間と公共の一覧が分かれていることに気づかないままIssueを作成してしまい失礼しました。早速のご対応ありがとうございました！
